DEBUG    urllib3.connectionpool:connectionpool.py:1053 Starting new HTTPS connection (1): petstore.swagger.io:443
DEBUG    urllib3.connectionpool:connectionpool.py:547 https://petstore.swagger.io:443 "PUT /v2/pet/ HTTP/1.1" 200 None
INFO     tests_pets:tests_pets.py:27 API call was made
